# Generated by Django 3.2.6 on 2021-08-20 14:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyerpatch',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='flyerpatch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='flyerpatch',
            name='flyer_count',
            field=models.IntegerField(verbose_name='Anzahl Bierdeckel'),
        ),
        migrations.AlterField(
            model_name='flyerpatch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer*in'),
        ),
        migrations.AlterField(
            model_name='flyerpatch',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Bereich'),
        ),
    ]
